CREATE TABLE IF NOT EXISTS `ai_user_pay_contract` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  `subscription_id` BIGINT DEFAULT NULL,
  `channel` VARCHAR(32) NOT NULL COMMENT 'wechat | alipay',
  `plan_id` VARCHAR(128) DEFAULT NULL COMMENT '微信委托代扣模板ID / 支付宝签约模板ID',
  `contract_code` VARCHAR(128) NOT NULL COMMENT '商户侧签约协议号',
  `contract_id` VARCHAR(128) DEFAULT NULL COMMENT '微信/支付宝侧协议ID',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending | signed | terminated | expired',
  `signed_time` DATETIME DEFAULT NULL,
  `terminated_time` DATETIME DEFAULT NULL,
  `terminate_mode` VARCHAR(32) DEFAULT NULL COMMENT 'user | merchant | system',
  `notify_url` VARCHAR(512) DEFAULT NULL,
  `extra_json` JSON DEFAULT NULL COMMENT '渠道额外字段',
  `create_by` BIGINT DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT DEFAULT NULL,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_contract_code_channel` (`contract_code`, `channel`),
  UNIQUE KEY `uk_user_channel_signed` (`user_id`, `channel`, `status`),
  KEY `idx_subscription_id` (`subscription_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_contract_id` (`contract_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户支付自动扣款签约协议';
