CREATE TABLE IF NOT EXISTS ai_recycle_bin (
  id INT NOT NULL AUTO_INCREMENT COMMENT '回收记录ID',
  tenant_id INT NOT NULL COMMENT '租户ID',
  resource_type VARCHAR(32) NOT NULL COMMENT '资源类型：project/brief/script',
  resource_id INT NOT NULL COMMENT '原资源ID',
  resource_name VARCHAR(255) NOT NULL COMMENT '删除时资源名称快照',
  parent_id INT DEFAULT NULL COMMENT '所属项目ID等父级资源ID',
  snapshot_json JSON DEFAULT NULL COMMENT '恢复和展示所需的轻量快照',
  retention_days INT NOT NULL DEFAULT 7 COMMENT '本次保留天数',
  recycle_status VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active/restored/purged',
  deleted_by INT NOT NULL COMMENT '执行删除的用户ID',
  deleted_at DATETIME NOT NULL COMMENT '删除时间',
  expire_at DATETIME NOT NULL COMMENT '自动清理时间',
  restore_time DATETIME DEFAULT NULL COMMENT '恢复时间',
  purge_time DATETIME DEFAULT NULL COMMENT '永久删除时间',
  create_by INT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by INT DEFAULT NULL COMMENT '更新人',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  KEY idx_ai_recycle_owner_active (tenant_id, deleted_by, recycle_status, deleted_at),
  KEY idx_ai_recycle_expire (recycle_status, expire_at),
  KEY idx_ai_recycle_resource (tenant_id, resource_type, resource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户回收站';
