// Run against Vite. All /api requests are intercepted: no model calls, uploads or account mutations.
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.DIRECTOR_PLAYWRIGHT_MODULE || 'playwright');
const outputDir = process.env.DIRECTOR_QA_OUTPUT || '/tmp/ai-script-director-qa';
await mkdir(outputDir, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.DIRECTOR_CHROMIUM_PATH ? { executablePath: process.env.DIRECTOR_CHROMIUM_PATH } : {}) });
const page = await browser.newPage({ viewport: { width: 1440, height: 920 }, deviceScaleFactor: 1 });
const failures = [];
page.on('pageerror', error => failures.push(error.message));
let uploadedPng;
let uploadCount = 0;
let failUpload = false;
await page.route('**/api/**', async route => {
  const request = route.request(); const url = new URL(request.url());
  if (!url.pathname.startsWith('/api/')) { await route.continue(); return; }
  let data = { list: [], total: 0, page: 1, pageSize: 20, items: [], activeCount: 0, pendingCount: 0, runningCount: 0, concurrency: 1 };
  if (url.pathname.endsWith('/auth/user-info')) data = { id: 'qa-user', username: '导演台验收', phone: '13800000000', email: 'director-qa@example.test' };
  if (url.pathname.endsWith('/workflow/models')) data = [];
  if (url.pathname.endsWith('/files/upload')) {
    if (failUpload) { await route.fulfill({ status: 500, json: { code: 50000, message: 'QA: upload failure', data: null } }); return; }
    const body = request.postDataBuffer();
    const signature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
    const start = body.indexOf(signature);
    assert.ok(start >= 0, 'upload contains real PNG bytes');
    const end = body.indexOf(Buffer.from('\r\n--'), start);
    uploadedPng = body.subarray(start, end); uploadCount += 1;
    data = { url: '/director-qa-upload.png', objectKey: 'director/qa.png', contentType: 'image/png' };
  }
  await route.fulfill({ json: { code: 0, message: 'success', data } });
});
await page.route('**/director-qa-upload.png', route => route.fulfill({ contentType: 'image/png', body: uploadedPng || Buffer.alloc(0) }));
await page.addInitScript(() => { localStorage.setItem('token', 'director-qa-mocked-token'); localStorage.setItem('needsPhoneBinding', 'false'); localStorage.setItem('needsEmailBinding', 'false'); });
const state = () => page.evaluate(async () => {
  const { useWorkflowStore } = await import('/src/stores/workflowStore.ts');
  return { nodes: useWorkflowStore.getState().nodes, edges: useWorkflowStore.getState().edges };
});
try {
  await page.goto(`${process.env.DIRECTOR_BASE_URL || 'http://127.0.0.1:4174'}/workspace?step=visual`);
  await page.getByRole('button', { name: '添加节点', exact: true }).click();
  await page.getByRole('button', { name: '导演台 3D' }).click();
  const studio = page.getByRole('dialog', { name: '3D 导演台', exact: true });
  await studio.waitFor();
  await page.locator('.director-viewport-canvas').waitFor();
  await page.waitForFunction(() => document.querySelector('.director-viewport-canvas')?.width > 100);
  assert.equal(await page.locator('.director-viewport-error').count(), 0, 'WebGL initialized');
  await page.getByLabel('场景名称', { exact: true }).fill('电商产品构图');
  await page.getByRole('button', { name: '添加人物', exact: true }).click();
  await page.getByLabel('对象名称', { exact: true }).fill('展示模特');
  await page.getByLabel('角色姿势', { exact: true }).selectOption('wave');
  await page.getByLabel('位置 / m X', { exact: true }).fill('-1.5');
  await page.getByRole('button', { name: '锁定展示模特', exact: true }).click();
  assert.equal(await page.getByLabel('对象名称', { exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: '解锁展示模特', exact: true }).click();
  await page.getByRole('button', { name: '复制对象', exact: true }).click();
  assert.equal(await page.getByLabel('对象名称', { exact: true }).inputValue(), '展示模特 副本');
  await page.getByRole('button', { name: '撤销导演台操作', exact: true }).click();
  assert.equal((await state()).nodes.find(node => node.data.kind === 'director').data.directorScene.objects.length, 4);
  await page.getByRole('button', { name: '重做导演台操作', exact: true }).click();
  assert.equal((await state()).nodes.find(node => node.data.kind === 'director').data.directorScene.objects.length, 5);
  await page.locator('.director-tree-select').filter({ hasText: '展示模特 副本' }).click();
  await page.getByRole('button', { name: /删除对象/ }).click();
  assert.equal((await state()).nodes.find(node => node.data.kind === 'director').data.directorScene.objects.length, 4);
  await page.locator('.director-tree-select').filter({ hasText: '机位 1' }).click();
  await page.getByRole('button', { name: '缓慢推进 ↗', exact: true }).click();
  let scene = (await state()).nodes.find(node => node.data.kind === 'director').data.directorScene;
  assert.equal(scene.cameras[0].keyframes.length, 2);
  await page.getByRole('button', { name: '播放预演', exact: true }).click();
  await page.waitForFunction(() => Number(document.querySelector('input[aria-label="时间轴播放位置"]').value) > 0.5);
  await page.getByRole('button', { name: '暂停预演', exact: true }).click();
  await page.getByRole('button', { name: '回到起点', exact: true }).click();
  await page.getByLabel('视野角度', { exact: true }).fill('45');
  scene = (await state()).nodes.find(node => node.data.kind === 'director').data.directorScene;
  assert.equal(scene.cameras[0].keyframes[0].fov, 45, 'parameter edits update current keyframe');
  await page.screenshot({ path: `${outputDir}/director-camera.png` });
  await page.getByRole('button', { name: '导演视角', exact: true }).click();
  await page.locator('.director-view-switch button.is-active').filter({ hasText: '导演视角' }).waitFor();
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  await page.screenshot({ path: `${outputDir}/director-studio.png` });
  const pngDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: '下载当前机位 PNG', exact: true }).click();
  await (await pngDownload).saveAs(`${outputDir}/director-frame.png`);
  const jsonDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: /导出工程/ }).click();
  const json = await jsonDownload;
  await json.saveAs(`${outputDir}/director-scene.json`);
  await page.getByLabel('场景名称', { exact: true }).fill('导入前的临时场景');
  await page.locator('.director-library-footer input[type=file]').setInputFiles(`${outputDir}/director-scene.json`);
  await page.waitForFunction(() => document.querySelector('input[aria-label="场景名称"]').value === '电商产品构图');
  await page.getByRole('button', { name: '返回画布', exact: true }).click();
  await studio.waitFor({ state: 'detached' });
  await page.reload();
  await page.getByRole('button', { name: /^打开导演台：/ }).click();
  await studio.waitFor();
  assert.equal(await page.getByLabel('场景名称', { exact: true }).inputValue(), '电商产品构图', 'scene survives reload');
  scene = (await state()).nodes.find(node => node.data.kind === 'director').data.directorScene;
  assert.equal(scene.cameras[0].keyframes[0].fov, 45);
  failUpload = true;
  await page.getByRole('button', { name: '截图到画布', exact: false }).click();
  await page.locator('.director-busy-shield').waitFor({ state: 'detached' });
  assert.equal(await studio.count(), 1, 'failed upload keeps editor open');
  assert.equal((await state()).nodes.filter(node => node.id.startsWith('director-frame')).length, 0, 'no fake result after failed upload');
  failUpload = false;
  await page.getByRole('button', { name: '截图到画布', exact: false }).click();
  await studio.waitFor({ state: 'detached' });
  const after = await state();
  const director = after.nodes.find(node => node.data.kind === 'director');
  const result = after.nodes.find(node => node.id.startsWith('director-frame'));
  assert.equal(uploadCount, 1);
  assert.ok(uploadedPng.length > 10000, 'actual rendered content uploaded');
  assert.equal(director.data.assetUrl, result.data.assetUrl);
  assert.ok(after.edges.some(edge => edge.source === director.id && edge.target === result.id && edge.sourceHandle === 'right' && edge.targetHandle === 'left'));
  await page.getByRole('button', { name: '适配画布', exact: true }).click();
  await page.locator('.ant-message-notice').last().waitFor({ state: 'detached' });
  await page.screenshot({ path: `${outputDir}/director-canvas-result.png` });
  await page.getByRole('button', { name: /^打开导演台：/ }).click();
  await page.setViewportSize({ width: 1024, height: 768 });
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  await page.screenshot({ path: `${outputDir}/director-1024.png` });
  assert.equal(await page.evaluate(() => document.querySelector('.director-studio').scrollWidth <= window.innerWidth), true, 'no horizontal overflow');
  assert.equal(await page.locator('.director-track-label').first().evaluate(element => Math.round(element.getBoundingClientRect().height)), 29, 'timeline rows are compact and aligned');
  await page.getByLabel('场景名称', { exact: true }).fill('需要重新截图');
  const changed = await state();
  assert.equal(changed.nodes.find(node => node.data.kind === 'director').data.assetUrl, undefined, 'editing invalidates the current shot');
  assert.ok(changed.nodes.find(node => node.id.startsWith('director-frame')).data.assetUrl, 'exported history frame is preserved');
  await page.evaluate(() => {
    window.__directorOriginalStorageSet = Storage.prototype.setItem;
    Storage.prototype.setItem = function(key, value) {
      if (key.startsWith('ai-script:visual-workflow:')) throw new DOMException('QA: quota', 'QuotaExceededError');
      return window.__directorOriginalStorageSet.call(this, key, value);
    };
  });
  await page.getByRole('button', { name: /保存项目/ }).click();
  await page.waitForFunction(() => document.querySelector('.director-save-status')?.textContent.includes('保存失败'));
  await page.getByRole('button', { name: '返回画布', exact: true }).click();
  assert.equal(await studio.count(), 1, 'quota failure does not silently discard editor');
  await page.evaluate(() => { Storage.prototype.setItem = window.__directorOriginalStorageSet; delete window.__directorOriginalStorageSet; });
  assert.deepEqual(failures, [], 'no browser runtime errors');
  console.log(JSON.stringify({ passed: true, checks: ['menu integration', 'WebGL', 'object transforms', 'pose', 'lock/unlock', 'duplicate', 'delete', 'undo/redo', 'camera preset', 'timeline playback', 'keyframe edits', 'PNG export', 'JSON export/import', 'reload persistence', 'upload failure', 'PNG upload + result edge', '1024px layout', 'snapshot invalidation', 'storage quota failure'], pngBytes: uploadedPng.length, outputDir }, null, 2));
} catch (error) {
  await page.screenshot({ path: `${outputDir}/failure.png` });
  console.error('Browser errors:', failures);
  console.error('Layout:', await page.evaluate(() => ['.director-timeline', '.director-tracks', '.director-track', '.director-track-label', '.director-track-svg'].map(selector => { const element = document.querySelector(selector); return [selector, element?.getBoundingClientRect().toJSON(), element && { display: getComputedStyle(element).display, height: getComputedStyle(element).height, minHeight: getComputedStyle(element).minHeight }]; })));
  throw error;
} finally { await browser.close(); }
